sudo: required
services: 
  - docker

before_install:
  - docker build -t colin/docker-react -f Dockerfile.dev .

script: 
  - docker run colin/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-env"
  bucket-name: elasticbeanstalk-us-east-1-947251449638
  bucket-path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

